### ISSUE TITLE
all in dify场景下语音播报失败

### ISSUE THREAD

**Issue by leoterry-ulrica** [wan-h/awesome-digital-human-live2d#46]
```
[DEBUG]2024-11-28 14:10:13,331 File 'difyAgent.py',line 132: [AGENT] Engine response: {'event': 'message', 'conversation_id': 'ad290166-cfb1-4512-973a-41ad0d15536c', 'message_id': '15a48e0d-50a6-4e9f-992e-169cce959d80', 'created_at': 1732803012, 'task_id': '0e13a0f8-9707-4036-9fbe-878056a72d5c', 'id': '15a48e0d-50a6-4e9f-992e-169cce959d80', 'answer': '', 'from_variable_selector': ['llm', 'text']}
INFO:     192.168.1.181:59624 - "OPTIONS /adh/tts/v0/infer HTTP/1.1" 200 OK
[DEBUG]2024-11-28 14:10:13,610 File 'difyTTS.py',line 42: [TTS] Engine input: 你好！有什么问题想和我聊聊吗？
[ERROR]2024-11-28 14:10:18,740 File 'difyTTS.py',line 60: [TTS] Engine run failed: timed out
Traceback (most recent call last):
  File "/usr/local/lib/python3.10/dist-packages/httpx/_transports/default.py", line 69, in map_httpcore_exceptions
    yield
  File "/usr/local/lib/python3.10/dist-packages/httpx/_transports/default.py", line 233, in handle_request
    resp = self._pool.handle_request(req)
  File "/usr/local/lib/python3.10/dist-packages/httpcore/_sync/connection_pool.py", line 256, in handle_request
    raise exc from None
  File "/usr/local/lib/python3.10/dist-packages/httpcore/_sync/connection_pool.py", line 236, in handle_request
    response = connection.handle_request(
  File "/usr/local/lib/python3.10/dist-packages/httpcore/_sync/connection.py", line 103, in handle_request
    return self._connection.handle_request(request)
  File "/usr/local/lib/python3.10/dist-packages/httpcore/_sync/http11.py", line 136, in handle_request
    raise exc
  File "/usr/local/lib/python3.10/dist-packages/httpcore/_sync/http11.py", line 106, in handle_request
    ) = self._receive_response_headers(**kwargs)
  File "/usr/local/lib/python3.10/dist-packages/httpcore/_sync/http11.py", line 177, in _receive_response_headers
    event = self._receive_event(timeout=timeout)
  File "/usr/local/lib/python3.10/dist-packages/httpcore/_sync/http11.py", line 217, in _receive_event
    data = self._network_stream.read(
  File "/usr/local/lib/python3.10/dist-packages/httpcore/_backends/sync.py", line 126, in read
    with map_exceptions(exc_map):
  File "/usr/lib/python3.10/contextlib.py", line 153, in __exit__
    self.gen.throw(typ, value, traceback)
  File "/usr/local/lib/python3.10/dist-packages/httpcore/_exceptions.py", line 14, in map_exceptions
    raise to_exc(exc) from exc
httpcore.ReadTimeout: timed out

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/workspace/digitalHuman/engine/tts/difyTTS.py", line 47, in run
    resp = httpx.post(API_URL + "/text-to-audio", json=payload, headers=headers)
  File "/usr/local/lib/python3.10/dist-packages/httpx/_api.py", line 319, in post
    return request(
  File "/usr/local/lib/python3.10/dist-packages/httpx/_api.py", line 106, in request
    return client.request(
  File "/usr/local/lib/python3.10/dist-packages/httpx/_client.py", line 827, in request
    return self.send(request, auth=auth, follow_redirects=follow_redirects)
  File "/usr/local/lib/python3.10/dist-packages/httpx/_client.py", line 914, in send
    response = self._send_handling_auth(
  File "/usr/local/lib/python3.10/dist-packages/httpx/_client.py", line 942, in _send_handling_auth
    response = self._send_handling_redirects(
  File "/usr/local/lib/python3.10/dist-packages/httpx/_client.py", line 979, in _send_handling_redirects
    response = self._send_single_request(request)
  File "/usr/local/lib/python3.10/dist-packages/httpx/_client.py", line 1015, in _send_single_request
    response = transport.handle_request(request)
  File "/usr/local/lib/python3.10/dist-packages/httpx/_transports/default.py", line 232, in handle_request
    with map_httpcore_exceptions():
  File "/usr/lib/python3.10/contextlib.py", line 153, in __exit__
    self.gen.throw(typ, value, traceback)
  File "/usr/local/lib/python3.10/dist-packages/httpx/_transports/default.py", line 86, in map_httpcore_exceptions
    raise mapped_exc(message) from exc
httpx.ReadTimeout: timed out
[ERROR]2024-11-28 14:10:18,741 File 'reponse.py',line 41: TTS engine run failed
INFO:     192.168.1.181:59624 - "POST /adh/tts/v0/infer HTTP/1.1" 200 OK
ERROR:    Exception in ASGI application
Traceback (most recent call last):
  File "/usr/local/lib/python3.10/dist-packages/uvicorn/protocols/websockets/websockets_impl.py", line 254, in run_asgi
    result = await self.app(self.scope, self.asgi_receive, self.asgi_send)
  File "/usr/local/lib/python3.10/dist-packages/uvicorn/middleware/proxy_headers.py", line 84, in __call__
    return await self.app(scope, receive, send)
  File "/usr/local/lib/python3.10/dist-packages/fastapi/applications.py", line 1106, in __call__
    await super().__call__(scope, receive, send)
  File "/usr/local/lib/python3.10/dist-packages/starlette/applications.py", line 122, in __call__
    await self.middleware_stack(scope, receive, send)
  File "/usr/local/lib/python3.10/dist-packages/starlette/middleware/errors.py", line 149, in __call__
    await self.app(scope, receive, send)
  File "/usr/local/lib/python3.10/dist-packages/starlette/middleware/cors.py", line 75, in __call__
    await self.app(scope, receive, send)
  File "/usr/local/lib/python3.10/dist-packages/starlette/middleware/exceptions.py", line 79, in __call__
    raise exc
  File "/usr/local/lib/python3.10/dist-packages/starlette/middleware/exceptions.py", line 68, in __call__
    await self.app(scope, receive, sender)
  File "/usr/local/lib/python3.10/dist-packages/fastapi/middleware/asyncexitstack.py", line 20, in __call__
    raise e
  File "/usr/local/lib/python3.10/dist-packages/fastapi/middleware/asyncexitstack.py", line 17, in __call__
    await self.app(scope, receive, send)
  File "/usr/local/lib/python3.10/dist-packages/starlette/routing.py", line 718, in __call__
    await route.handle(scope, receive, send)
  File "/usr/local/lib/python3.10/dist-packages/starlette/routing.py", line 341, in handle
    await self.app(scope, receive, send)
  File "/usr/local/lib/python3.10/dist-packages/starlette/routing.py", line 82, in app
    await func(session)
  File "/usr/local/lib/python3.10/dist-packages/fastapi/routing.py", line 325, in app
    await dependant.call(**values)
  File "/workspace/digitalHuman/server/commonApi.py", line 51, in websocket_heartbeat
    await ws_manager.send_personal_message("pong", websocket)
  File "/workspace/digitalHuman/server/commonApi.py", line 32, in send_personal_message
    await ws.send_text(message)
  File "/usr/local/lib/python3.10/dist-packages/starlette/websockets.py", line 163, in send_text
    await self.send({"type": "websocket.send", "text": data})
  File "/usr/local/lib/python3.10/dist-packages/starlette/websockets.py", line 85, in send
    await self._send(message)
  File "/usr/local/lib/python3.10/dist-packages/starlette/middleware/exceptions.py", line 65, in sender
    await send(message)
  File "/usr/local/lib/python3.10/dist-packages/uvicorn/protocols/websockets/websockets_impl.py", line 344, in asgi_send
    await self.send(data)  # type: ignore[arg-type]
  File "/usr/local/lib/python3.10/dist-packages/websockets/legacy/protocol.py", line 630, in send
    await self.ensure_open()
  File "/usr/local/lib/python3.10/dist-packages/websockets/legacy/protocol.py", line 940, in ensure_open
    raise self.connection_closed_exc()
websockets.exceptions.ConnectionClosedOK: received 1005 (no status received [internal]); then sent 1005 (no status received [internal])
INFO:     connection closed
INFO:     ('192.168.1.181', 59659) - "WebSocket /adh/common/v0/heartbeat" [accepted]

```

**Comment by wan-h** [comment]
超时问题我晚点优化一下

**Comment by leoterry-ulrica** [comment]
> 超时问题我晚点优化一下

好的  期待修复

**Comment by SAnBlog** [comment]
+1

**Comment by wan-h** [comment]
已经做了一版fix，dify cloud上做了验证，本地部署使用最新版本的dify， 之前dify的tts接口有点Bug

**Comment by wan-h** [comment]
已经做了一版fix，dify cloud上做了验证，本地部署使用最新版本的dify， 之前dify的tts接口有点Bug

**Comment by SAnBlog** [comment]
是确实可以语音播报了,但是偶尔会出现只播报一半的情况,丢失后续的部分

**Comment by leoterry-ulrica** [comment]
> 已经做了一版fix，dify cloud上做了验证，本地部署使用最新版本的dify， 之前dify的tts接口有点Bug

还有个问题就是修改环境变量的server端口，其实不生效，例如我修改成4000。
```
NEXT_PUBLIC_ADH_SERVER_PORT=4000
```
docker-compose-quickStart.yaml中也把adh_server的对外映射端口为4000。
前端请求的时候依然给8000端口发请求：
![image](https://github.com/user-attachments/assets/a1059c43-9ec8-4d18-8414-e29b9c64ea72)

**Comment by wan-h** [comment]
docker-compose up --build -d, 使用这个重新打包，你使用docker-compose-quickStart.yaml相当于直接拉去了阿里云构建好的镜像，你本地修改是没有生效的

**Comment by leoterry-ulrica** [comment]
> docker-compose up --build -d, 使用这个重新打包，你使用docker-compose-quickStart.yaml相当于直接拉去了阿里云构建好的镜像，你本地修改是没有生效的

那其实要允许使用者可以通过环境变量的方式传入更友好。

**Comment by wan-h** [comment]
这个本身就是docker-compose的参数变量，所有有两个docker-compose yaml文件，根据自己的情况选择使用

**Comment by murray-z** [comment]
> 是确实可以语音播报了,但是偶尔会出现只播报一半的情况,丢失后续的部分

这个解决了吗？我这里一直都是播报一半。
