### ISSUE TITLE
每次语音播报的时候都是只有前半部分

### ISSUE THREAD

**Issue by murray-z** [wan-h/awesome-digital-human-live2d#50]
每次语音播报的时候都是只有前半部分

**Comment by zm1990s** [comment]
遇到同样的问题，试过通义及 Openai 的模型，都是一样的问题。
日志中只有第一句的 TTS 执行完毕了，后面的报错：
```
# 下面这句会成功执行：
[DEBUG]2024-12-31 12:39:42,556 File 'difyTTS.py',line 46: [TTS] Engine input: 我理解您可能有自己的原因一直重复打招呼,

# 下面的执行失败：
[DEBUG]2024-12-31 12:39:43,216 File 'difyTTS.py',line 46: [TTS] Engine input: 但是这样的对话可能无法为您提供有价值的帮助或信息。
[ERROR]2024-12-31 12:39:43,217 File 'difyTTS.py',line 65: [TTS] Engine run failed: Task <Task pending name='Task-739' coro=<RequestResponseCycle.run_asgi() running at /usr/local/lib/python3.8/dist-packages/uvicorn/protocols/http/h11_impl.py:404> cb=[set.discard()]> got Future <Future pending> attached to a different loop
Traceback (most recent call last):
  File "/workspace/digitalHuman/engine/tts/difyTTS.py", line 47, in run
    async with self.asyncLock:
  File "/usr/lib/python3.8/asyncio/locks.py", line 97, in __aenter__
    await self.acquire()
  File "/usr/lib/python3.8/asyncio/locks.py", line 203, in acquire
    await fut
RuntimeError: Task <Task pending name='Task-739' coro=<RequestResponseCycle.run_asgi() running at /usr/local/lib/python3.8/dist-packages/uvicorn/protocols/http/h11_impl.py:404> cb=[set.discard()]> got Future <Future pending> attached to a different loop
[ERROR]2024-12-31 12:39:43,220 File 'reponse.py',line 41: TTS engine run failed
INFO:     172.18.0.1:57868 - "POST /adh/tts/v0/infer HTTP/1.1" 200 OK
[DEBUG]2024-12-31 12:39:43,248 File 'difyAgent.py',line 134: [AGENT] Engine response: {'event': 'message', 'conversation_id': '08fdece1-fe1c-438c-8015-996770e8420f', 'message_id': 'e8f6fb61-eb26-4774-905a-3fb9bde4cc7a', 'created_at': 1735619980, 'task_id': 'ca6a1f3e-99c9-41d5-a430-d1a5f3d374f1', 'id': 'e8f6fb61-eb26-4774-905a-3fb9bde4cc7a', 'answer': '为一个AI', 'from_variable_selector': ['1735617957308', 'text']}
[DEBUG]2024-12-31 12:39:43,300 File 'difyAgent.py',line 134: [AGENT] Engine response: {'event': 'message', 'conversation_id': '08fdece1-fe1c-438c-8015-996770e8420f', 'message_id': 'e8f6fb61-eb26-4774-905a-3fb9bde4cc7a', 'created_at': 1735619980, 'task_id': 'ca6a1f3e-99c9-41d5-a430-d1a5f3d374f1', 'id': 'e8f6fb61-eb26-4774-905a-3fb9bde4cc7a', 'answer': '助手,我', 'from_variable_selector': ['1735617957308', 'text']}
[DEBUG]2024-12-31 12:39:43,308 File 'difyTTS.py',line 46: [TTS] Engine input: 作为一个AI助手,
[ERROR]2024-12-31 12:39:43,309 File 'difyTTS.py',line 65: [TTS] Engine run failed: Task <Task pending name='Task-740' coro=<RequestResponseCycle.run_asgi() running at /usr/local/lib/python3.8/dist-packages/uvicorn/protocols/http/h11_impl.py:404> cb=[set.discard()]> got Future <Future pending> attached to a different loop
Traceback (most recent call last):
  File "/workspace/digitalHuman/engine/tts/difyTTS.py", line 47, in run
    async with self.asyncLock:
  File "/usr/lib/python3.8/asyncio/locks.py", line 97, in __aenter__
    await self.acquire()
  File "/usr/lib/python3.8/asyncio/locks.py", line 203, in acquire
    await fut
RuntimeError: Task <Task pending name='Task-740' coro=<RequestResponseCycle.run_asgi() running at /usr/local/lib/python3.8/dist-packages/uvicorn/protocols/http/h11_impl.py:404> cb=[set.discard()]> got Future <Future pending> attached to a different loop
[ERROR]2024-12-31 12:39:43,311 File 'reponse.py',line 41: TTS engine run failed
INFO:     172.18.0.1:57868 - "POST /adh/tts/v0/infer HTTP/1.1" 200 OK


```

**Comment by zm1990s** [comment]
修改了 difyTTS.py 的这两处，算是可以正常工作了，只是稍有点延迟。
<img width="910" alt="image" src="https://github.com/user-attachments/assets/6021ec53-0c0f-494e-b5b1-0cd31972c17b" />

**Comment by wan-h** [comment]
最新版的dify 可以把 async with self.asyncLock 删除了, 这个兼容之前版本并发请求的bug

**Comment by liduang** [comment]
请问咋根本解决？

**Comment by liduang** [comment]
更新到dify 最新的v0.14.2，删除 async with self.asyncLock，不报错了，但还是后半部分对话没有播报

**Comment by zm1990s** [comment]
> 更新到dify 最新的v0.14.2，删除 async with self.asyncLock，不报错了，但还是后半部分对话没有播报

你有没有开启“自动播放”功能？关掉试试

**Comment by zyxchaos0314** [comment]
同样也出现这个问题，报错问题解决了，但仍然只说一句话。然后发现将Default TTS改为edgeAPI.yaml，可以实现播报。

**Comment by wan-h** [comment]
你们贴一下你们后端的报错日志看看

**Comment by zyxchaos0314** [comment]
> 你们贴一下你们后端的报错日志看看

DEBUG]2025-01-07 14:33:20,046 File 'difyAgent.py',line 134: [AGENT] Engine response: {'event': 'message', 'conversation_id': '54a795a0-043f-43c7-9520-92d18be74840', 'message_id': '6903e96d-46fd-4edc-b45c-a2233c0325d6', 'created_at': 1736231567, 'task_id': 'e335f48c-f208-4cc4-836d-3b34368b29fe', 'id': '6903e96d-46fd-4edc-b45c-a2233c0325d6', 'answer': '，请', 'from_variable_selector': ['llm', 'text']}
[DEBUG]2025-01-07 14:33:20,059 File 'difyTTS.py',line 46: [TTS] Engine input: 如果遇到任何问题，
[ERROR]2025-01-07 14:33:20,059 File 'difyTTS.py',line 65: [TTS] Engine run failed: Task <Task pending name='Task-191' coro=<RequestResponseCycle.run_asgi() running at /usr/local/lib/python3.8/dist-packages/uvicorn/protocols/http/h11_impl.py:404> cb=[set.discard()]> got Future <Future pending> attached to a different loop
Traceback (most recent call last):
  File "/workspace/digitalHuman/engine/tts/difyTTS.py", line 47, in run
    async with self.asyncLock:
  File "/usr/lib/python3.8/asyncio/locks.py", line 97, in __aenter__
    await self.acquire()
  File "/usr/lib/python3.8/asyncio/locks.py", line 203, in acquire
    await fut
RuntimeError: Task <Task pending name='Task-191' coro=<RequestResponseCycle.run_asgi() running at /usr/local/lib/python3.8/dist-packages/uvicorn/protocols/http/h11_impl.py:404> cb=[set.discard()]> got Future <Future pending> attached to a different loop
[ERROR]2025-01-07 14:33:20,059 File 'reponse.py',line 41: TTS engine run failed
INFO:     10.255.255.2:52561 - "POST /adh/tts/v0/infer HTTP/1.1" 200 OK
